apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patchesStrategicMerge:
  - replicas.yaml     # your Deployment patch

configMapGenerator:
  - name: mykustom-map
    env: config.properties
